[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Compiler settings
solc = "0.8.24"
auto_detect_solc = true



# Stricter compiler settings
optimizer = true
optimizer_runs = 200
via_ir = true

# Error handling
extra_output = ["storageLayout", "metadata"]

[rpc_endpoints]
devnet = "${DEVNET_RPC_URL}"
localnet="${LOCAL_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
